services:
    app.admin.post:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User Admin", label: "Users" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - AppBundle:UserAdmin
        calls:
            - [ setTranslationDomain, [AppBundle]]